# Generated by Django 3.2.3 on 2022-06-10 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultaMedica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
